package com.xworkz.bag.boot;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.xworkz.bag.beans.Apple;
import com.xworkz.bag.beans.Bag;
import com.xworkz.bag.beans.Bathroom;
import com.xworkz.bag.beans.Beanch;
import com.xworkz.bag.beans.Bear;
import com.xworkz.bag.beans.Bed;
import com.xworkz.bag.beans.Belt;
import com.xworkz.bag.beans.Bike;
import com.xworkz.bag.beans.Book;
import com.xworkz.bag.beans.Bottle;
import com.xworkz.bag.beans.Bus;
import com.xworkz.bag.beans.Cement;
import com.xworkz.bag.beans.Chair;
import com.xworkz.bag.beans.Cloth;
import com.xworkz.bag.beans.Dog;
import com.xworkz.bag.beans.Door;
import com.xworkz.bag.beans.Fan;
import com.xworkz.bag.beans.Fridge;
import com.xworkz.bag.beans.Fruit;
import com.xworkz.bag.beans.Hair;
import com.xworkz.bag.beans.Hero;
import com.xworkz.bag.beans.Iron;
import com.xworkz.bag.beans.Laptop;
import com.xworkz.bag.beans.Lolipop;
import com.xworkz.bag.beans.Mall;
import com.xworkz.bag.beans.Man;
import com.xworkz.bag.beans.Manoj;
import com.xworkz.bag.beans.Mat;
import com.xworkz.bag.beans.Metro;
import com.xworkz.bag.beans.Mobile;
import com.xworkz.bag.beans.Pen;
import com.xworkz.bag.beans.Pencil;
import com.xworkz.bag.beans.Petrol;
import com.xworkz.bag.beans.Pg;
import com.xworkz.bag.beans.Pillow;
import com.xworkz.bag.beans.Plane;
import com.xworkz.bag.beans.Price;
import com.xworkz.bag.beans.Pump;
import com.xworkz.bag.beans.Rubber;
import com.xworkz.bag.beans.Sallon;
import com.xworkz.bag.beans.Shirt;
import com.xworkz.bag.beans.Slipper;
import com.xworkz.bag.beans.Table;
import com.xworkz.bag.beans.Tennis;
import com.xworkz.bag.beans.Train;
import com.xworkz.bag.beans.Tree;
import com.xworkz.bag.beans.Vegitable;
import com.xworkz.bag.beans.Vibrator;
import com.xworkz.bag.beans.Window;
import com.xworkz.bag.beans.Wire;
import com.xworkz.bag.configuration.BagConfiguration;

public class BagBoot {

	public static void main(String[] args) {

		ApplicationContext context = new AnnotationConfigApplicationContext(BagConfiguration.class);
		System.out.println("HashCode of Apple:" + context.getBean(Apple.class).hashCode());
		System.out.println("HashCode of Bag:" + context.getBean(Bag.class).hashCode());
		System.out.println("HashCode of Bathroom:" + context.getBean(Bathroom.class).hashCode());
		System.out.println("HashCode of Beanch:" + context.getBean(Beanch.class).hashCode());
		System.out.println("HashCode of Bear:" + context.getBean(Bear.class).hashCode());
		System.out.println("HashCode of Bed:" + context.getBean(Bed.class).hashCode());
		System.out.println("HashCode of Belt:" + context.getBean(Belt.class).hashCode());
		System.out.println("HashCode of Bike:" + context.getBean(Bike.class).hashCode());
		System.out.println("HashCode of Book:" + context.getBean(Book.class).hashCode());
		System.out.println("HashCode of Bottle:" + context.getBean(Bottle.class).hashCode());
		System.out.println("HashCode of Bullet:" + context.getBean(com.xworkz.bag.beans.Bullet.class).hashCode());
		System.out.println("HashCode of Bus:" + context.getBean(Bus.class).hashCode());
		System.out.println("HashCode of Cement:" + context.getBean(Cement.class).hashCode());
		System.out.println("HashCode of Chair:" + context.getBean(Chair.class).hashCode());
		System.out.println("HashCode of Cloth:" + context.getBean(Cloth.class).hashCode());
		System.out.println("HashCode of Dog:" + context.getBean(Dog.class).hashCode());
		System.out.println("HashCode of Door:" + context.getBean(Door.class).hashCode());
		System.out.println("HashCode of Fan:" + context.getBean(Fan.class).hashCode());
		System.out.println("HashCode of Fridge:" + context.getBean(Fridge.class).hashCode());
		System.out.println("HashCode of Fruit:" + context.getBean(Fruit.class).hashCode());
		System.out.println("HashCode of Hair:" + context.getBean(Hair.class).hashCode());
		System.out.println("HashCode of Hero:" + context.getBean(Hero.class).hashCode());
		System.out.println("HashCode of Iron:" + context.getBean(Iron.class).hashCode());
		System.out.println("HashCode of Laptop:" + context.getBean(Laptop.class).hashCode());
		System.out.println("HashCode of Lolipop:" + context.getBean(Lolipop.class).hashCode());
		System.out.println("HashCode of Mall:" + context.getBean(Mall.class).hashCode());
		System.out.println("HashCode of Man:" + context.getBean(Man.class).hashCode());
		System.out.println("HashCode of Manoj:" + context.getBean(Manoj.class).hashCode());
		System.out.println("HashCode of Mat:" + context.getBean(Mat.class).hashCode());
		System.out.println("HashCode of Metro:" + context.getBean(Metro.class).hashCode());
		System.out.println("HashCode of Mobile:" + context.getBean(Mobile.class).hashCode());
		System.out.println("HashCode of Pen:" + context.getBean(Pen.class).hashCode());
		System.out.println("HashCode of Pencil:" + context.getBean(Pencil.class).hashCode());
		System.out.println("HashCode of Petrol:" + context.getBean(Petrol.class).hashCode());
		System.out.println("HashCode of Pg:" + context.getBean(Pg.class).hashCode());
		System.out.println("HashCode of Pillow:" + context.getBean(Pillow.class).hashCode());
		System.out.println("HashCode of Plane:" + context.getBean(Plane.class).hashCode());
		System.out.println("HashCode of Price:" + context.getBean(Price.class).hashCode());
		System.out.println("HashCode of Pump:" + context.getBean(Pump.class).hashCode());
		System.out.println("HashCode of Rubber:" + context.getBean(Rubber.class).hashCode());
		System.out.println("HashCode of Sallon:" + context.getBean(Sallon.class).hashCode());
		System.out.println("HashCode of Shirt:" + context.getBean(Shirt.class).hashCode());
		System.out.println("HashCode of Slipper:" + context.getBean(Slipper.class).hashCode());
		System.out.println("HashCode of Table:" + context.getBean(Table.class).hashCode());
		System.out.println("HashCode of Tennis:" + context.getBean(Tennis.class).hashCode());
		System.out.println("HashCode of Train:" + context.getBean(Train.class).hashCode());
		System.out.println("HashCode of Tree:" + context.getBean(Tree.class).hashCode());
		System.out.println("HashCode of Vegitable:" + context.getBean(Vegitable.class).hashCode());
		System.out.println("HashCode of Vibrator:" + context.getBean(Vibrator.class).hashCode());
		System.out.println("HashCode of Window:" + context.getBean(Window.class).hashCode());
		System.out.println("HashCode of Wire:" + context.getBean(Wire.class).hashCode());
		System.out.println("HashCode of Email:" + context.getBean("email",String.class).hashCode());
		System.out.println("HashCode of bike1:" + context.getBean("bike1",String.class).hashCode());
		System.out.println("HashCode of bike2:" + context.getBean("bike2",String.class).hashCode());
		System.out.println("HashCode of bike3:" + context.getBean("bike3",String.class).hashCode());
		System.out.println("HashCode of bike4:" + context.getBean("bike4",String.class).hashCode());
		System.out.println("HashCode of bike5:" + context.getBean("bike5",String.class).hashCode());
		System.out.println("HashCode of bike6:" + context.getBean("bike6",String.class).hashCode());
		System.out.println("HashCode of bike7:" + context.getBean("bike7",String.class).hashCode());
		System.out.println("HashCode of bike8:" + context.getBean("bike8",String.class).hashCode());
		System.out.println("HashCode of bike9:" + context.getBean("bike9",String.class).hashCode());
		System.out.println("HashCode of bike10:" + context.getBean("bike10",String.class).hashCode());
		System.out.println("HashCode of bike11:" + context.getBean("bike11",String.class).hashCode());
		System.out.println("HashCode of bike12:" + context.getBean("bike12",String.class).hashCode());
		System.out.println("HashCode of bike13:" + context.getBean("bike13",String.class).hashCode());
		System.out.println("HashCode of bike14:" + context.getBean("bike14",String.class).hashCode());
		System.out.println("HashCode of bike15:" + context.getBean("bike15",String.class).hashCode());
		System.out.println("HashCode of bike16:" + context.getBean("bike16",String.class).hashCode());
		System.out.println("HashCode of bike17:" + context.getBean("bike17",String.class).hashCode());
		System.out.println("HashCode of bike18:" + context.getBean("bike18",String.class).hashCode());
		System.out.println("HashCode of bike19:" + context.getBean("bike19",String.class).hashCode());
		System.out.println("HashCode of bike20:" + context.getBean("bike20",String.class).hashCode());
		System.out.println("HashCode of bike21:" + context.getBean("bike21",String.class).hashCode());
		System.out.println("HashCode of bike22:" + context.getBean("bike22",String.class).hashCode());
		System.out.println("HashCode of bike23:" + context.getBean("bike23",String.class).hashCode());
		System.out.println("HashCode of bike24:" + context.getBean("bike24",String.class).hashCode());
		System.out.println("HashCode of bike25:" + context.getBean("bike25",String.class).hashCode());
		System.out.println("HashCode of bike26:" + context.getBean("bike26",String.class).hashCode());
		System.out.println("HashCode of bike27:" + context.getBean("bike27",String.class).hashCode());
		System.out.println("HashCode of bike28:" + context.getBean("bike28",String.class).hashCode());
		System.out.println("HashCode of bike29:" + context.getBean("bike29",String.class).hashCode());
		System.out.println("HashCode of bike30:" + context.getBean("bike30",String.class).hashCode());
		System.out.println("HashCode of bike31:" + context.getBean("bike31",String.class).hashCode());
		System.out.println("HashCode of bike32:" + context.getBean("bike32",String.class).hashCode());
		System.out.println("HashCode of bike33:" + context.getBean("bike33",String.class).hashCode());
		System.out.println("HashCode of bike34:" + context.getBean("bike34",String.class).hashCode());
		System.out.println("HashCode of bike35:" + context.getBean("bike35",String.class).hashCode());
		System.out.println("HashCode of bike36:" + context.getBean("bike36",String.class).hashCode());
		System.out.println("HashCode of bike37:" + context.getBean("bike37",String.class).hashCode());
		System.out.println("HashCode of bike38:" + context.getBean("bike38",String.class).hashCode());
		System.out.println("HashCode of bike39:" + context.getBean("bike39",String.class).hashCode());
		System.out.println("HashCode of bike40:" + context.getBean("bike40",String.class).hashCode());
		System.out.println("HashCode of bike41:" + context.getBean("bike41",String.class).hashCode());
		System.out.println("HashCode of bike42:" + context.getBean("bike42",String.class).hashCode());
		System.out.println("HashCode of bike43:" + context.getBean("bike43",String.class).hashCode());
		System.out.println("HashCode of bike44:" + context.getBean("bike44",String.class).hashCode());
		System.out.println("HashCode of bike45:" + context.getBean("bike45",String.class).hashCode());
		System.out.println("HashCode of bike46:" + context.getBean("bike46",String.class).hashCode());
		System.out.println("HashCode of bike47:" + context.getBean("bike47",String.class).hashCode());
		System.out.println("HashCode of bike48:" + context.getBean("bike48",String.class).hashCode());
		System.out.println("HashCode of bike49:" + context.getBean("bike49",String.class).hashCode());
		System.out.println("HashCode of bike50:" + context.getBean("bike50",String.class).hashCode());

	}

}
