package com.xworkz.bag.boot;

import javax.print.Doc;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.xworkz.bag.beans.*;
import com.xworkz.bag.configuration.BagConfiguration;

public class BagBoot {

	public static void main(String[] args) {

		ApplicationContext context = new AnnotationConfigApplicationContext(BagConfiguration.class);
		System.out.println("HashCode of Apple:" + context.getBean(Apple.class).hashCode());
		System.out.println("HashCode of Acid:" + context.getBean(Acid.class).hashCode());
		System.out.println("HashCode of Agricultur:" + context.getBean(Agriculture.class).hashCode());
		System.out.println("HashCode of Air:" + context.getBean(Air.class).hashCode());
		System.out.println("HashCode of Airplane:" + context.getBean(Airplane.class).hashCode());
		System.out.println("HashCode of Airport:" + context.getBean(Airport.class).hashCode());
		System.out.println("HashCode of Album:" + context.getBean(Album.class).hashCode());
		System.out.println("HashCode of Alcohol:" + context.getBean(Alcohol.class).hashCode());
		System.out.println("HashCode of Alligator:" + context.getBean(Alligator.class).hashCode());
		System.out.println("HashCode of Ant:" + context.getBean(Ant.class).hashCode());
		System.out.println("HashCode of Apron:" + context.getBean(Apron.class).hashCode());
		System.out.println("HashCode of Aquarium:" + context.getBean(Aquarium.class).hashCode());
		System.out.println("HashCode of Army:" + context.getBean(Army.class).hashCode());
		System.out.println("HashCode of Arrow:" + context.getBean(Arrow.class).hashCode());
		System.out.println("HashCode of Artist:" + context.getBean(Artist.class).hashCode());
		System.out.println("HashCode of Athlete:" + context.getBean(Athlete.class).hashCode());
		System.out.println("HashCode of Automobile:" + context.getBean(AutoMobile.class).hashCode());
		System.out.println("HashCode of Award:" + context.getBean(Award.class).hashCode());
		System.out.println("HashCode of Axe:" + context.getBean(Axe.class).hashCode());
		System.out.println("HashCode of Bag:" + context.getBean(Bag.class).hashCode());
		System.out.println("HashCode of Bathroom:" + context.getBean(Bathroom.class).hashCode());
		System.out.println("HashCode of Beanch:" + context.getBean(Beanch.class).hashCode());
		System.out.println("HashCode of Bear:" + context.getBean(Bear.class).hashCode());
		System.out.println("HashCode of Bed:" + context.getBean(Bed.class).hashCode());
		System.out.println("HashCode of Belt:" + context.getBean(Belt.class).hashCode());
		System.out.println("HashCode of Bike:" + context.getBean(Bike.class).hashCode());
		System.out.println("HashCode of Book:" + context.getBean(Book.class).hashCode());
		System.out.println("HashCode of Bottle:" + context.getBean(Bottle.class).hashCode());
		System.out.println("HashCode of Bullet:" + context.getBean(com.xworkz.bag.beans.Bullet.class).hashCode());
		System.out.println("HashCode of Bus:" + context.getBean(Bus.class).hashCode());
		System.out.println("HashCode of Cement:" + context.getBean(Cement.class).hashCode());
		System.out.println("HashCode of Chair:" + context.getBean(Chair.class).hashCode());
		System.out.println("HashCode of Cake:" + context.getBean(Cake.class).hashCode());
		System.out.println("HashCode of Camel:" + context.getBean(Camel.class).hashCode());
		System.out.println("HashCode of Camera:" + context.getBean(Camera.class).hashCode());
		System.out.println("HashCode of Candle:" + context.getBean(Candle.class).hashCode());
		System.out.println("HashCode of Card:" + context.getBean(Card.class).hashCode());
		System.out.println("HashCode of Carton:" + context.getBean(Carton.class).hashCode());
		System.out.println("HashCode of Chalk:" + context.getBean(Chalk.class).hashCode());
		System.out.println("HashCode of Cheese:" + context.getBean(Cheese.class).hashCode());
		System.out.println("HashCode of Child:" + context.getBean(Child.class).hashCode());
		System.out.println("HashCode of Chocolate:" + context.getBean(Chocolate.class).hashCode());
		System.out.println("HashCode of Cloud:" + context.getBean(Cloud.class).hashCode());
		System.out.println("HashCode of Corn:" + context.getBean(Corn.class).hashCode());
		System.out.println("HashCode of Cow:" + context.getBean(Cow.class).hashCode());
		System.out.println("HashCode of Deer:" + context.getBean(Deer.class).hashCode());
		System.out.println("HashCode of Desk:" + context.getBean(Desk.class).hashCode());
		System.out.println("HashCode of Dessert:" + context.getBean(Dessert.class).hashCode());
		System.out.println("HashCode of Devil:" + context.getBean(Devil.class).hashCode());
		System.out.println("HashCode of Diesel:" + context.getBean(Diesel.class).hashCode());
		System.out.println("HashCode of District:" + context.getBean(District.class).hashCode());
		System.out.println("HashCode of Divide:" + context.getBean(Divide.class).hashCode());
		System.out.println("HashCode of Doctor:" + context.getBean(Doctor.class).hashCode());
		System.out.println("HashCode of Doll:" + context.getBean(Doll.class).hashCode());
		System.out.println("HashCode of Dolphin:" + context.getBean(Dolphin.class).hashCode());
		System.out.println("HashCode of Door:" + context.getBean(Door.class).hashCode());
		System.out.println("HashCode of Driver:" + context.getBean(Driver.class).hashCode());
		System.out.println("HashCode of Drone:" + context.getBean(Drone.class).hashCode());
		System.out.println("HashCode of Drop:" + context.getBean(Drop.class).hashCode());
		System.out.println("HashCode of Duck:" + context.getBean(Duck.class).hashCode());
		System.out.println("HashCode of Dust:" + context.getBean(Dust.class).hashCode());
		System.out.println("HashCode of Earth:" + context.getBean(Earth.class).hashCode());
		System.out.println("HashCode of Engine:" + context.getBean(Engine.class).hashCode());
		System.out.println("HashCode of Erase:" + context.getBean(Erase.class).hashCode());
		System.out.println("HashCode of Dog:" + context.getBean(Dog.class).hashCode());
		System.out.println("HashCode of Door:" + context.getBean(Door.class).hashCode());
		System.out.println("HashCode of Fan:" + context.getBean(Fan.class).hashCode());
		System.out.println("HashCode of Fridge:" + context.getBean(Fridge.class).hashCode());
		System.out.println("HashCode of Fruit:" + context.getBean(Fruit.class).hashCode());
		System.out.println("HashCode of Hair:" + context.getBean(Hair.class).hashCode());
		System.out.println("HashCode of Hero:" + context.getBean(Hero.class).hashCode());
		System.out.println("HashCode of Iron:" + context.getBean(Iron.class).hashCode());
		System.out.println("HashCode of Laptop:" + context.getBean(Laptop.class).hashCode());
		System.out.println("HashCode of Lolipop:" + context.getBean(Lolipop.class).hashCode());
		System.out.println("HashCode of Mall:" + context.getBean(Mall.class).hashCode());
		System.out.println("HashCode of Man:" + context.getBean(Man.class).hashCode());
		System.out.println("HashCode of Manoj:" + context.getBean(Manoj.class).hashCode());
		System.out.println("HashCode of Mat:" + context.getBean(Mat.class).hashCode());
		System.out.println("HashCode of Metro:" + context.getBean(Metro.class).hashCode());
		System.out.println("HashCode of Mobile:" + context.getBean(Mobile.class).hashCode());
		System.out.println("HashCode of Pen:" + context.getBean(Pen.class).hashCode());
		System.out.println("HashCode of Pencil:" + context.getBean(Pencil.class).hashCode());
		System.out.println("HashCode of Petrol:" + context.getBean(Petrol.class).hashCode());
		System.out.println("HashCode of Pg:" + context.getBean(Pg.class).hashCode());
		System.out.println("HashCode of Pillow:" + context.getBean(Pillow.class).hashCode());
		System.out.println("HashCode of Plane:" + context.getBean(Plane.class).hashCode());
		System.out.println("HashCode of Price:" + context.getBean(Price.class).hashCode());
		System.out.println("HashCode of Pump:" + context.getBean(Pump.class).hashCode());
		System.out.println("HashCode of Rubber:" + context.getBean(Rubber.class).hashCode());
		System.out.println("HashCode of Sallon:" + context.getBean(Sallon.class).hashCode());
		System.out.println("HashCode of Shirt:" + context.getBean(Shirt.class).hashCode());
		System.out.println("HashCode of Slipper:" + context.getBean(Slipper.class).hashCode());
		System.out.println("HashCode of Table:" + context.getBean(Table.class).hashCode());
		System.out.println("HashCode of Tennis:" + context.getBean(Tennis.class).hashCode());
		System.out.println("HashCode of Train:" + context.getBean(Train.class).hashCode());
		System.out.println("HashCode of Tree:" + context.getBean(Tree.class).hashCode());
		System.out.println("HashCode of Vegitable:" + context.getBean(Vegitable.class).hashCode());
		System.out.println("HashCode of Vibrator:" + context.getBean(Vibrator.class).hashCode());
		System.out.println("HashCode of Window:" + context.getBean(Window.class).hashCode());
		System.out.println("HashCode of Wire:" + context.getBean(Wire.class).hashCode());
		System.out.println("HashCode of Email:" + context.getBean("email", String.class).hashCode());
		System.out.println("HashCode of bike1:" + context.getBean("bike1", String.class).hashCode());
		System.out.println("HashCode of bike2:" + context.getBean("bike2", String.class).hashCode());
		System.out.println("HashCode of bike3:" + context.getBean("bike3", String.class).hashCode());
		System.out.println("HashCode of bike4:" + context.getBean("bike4", String.class).hashCode());
		System.out.println("HashCode of bike5:" + context.getBean("bike5", String.class).hashCode());
		System.out.println("HashCode of bike6:" + context.getBean("bike6", String.class).hashCode());
		System.out.println("HashCode of bike7:" + context.getBean("bike7", String.class).hashCode());
		System.out.println("HashCode of bike8:" + context.getBean("bike8", String.class).hashCode());
		System.out.println("HashCode of bike9:" + context.getBean("bike9", String.class).hashCode());
		System.out.println("HashCode of bike10:" + context.getBean("bike10", String.class).hashCode());
		System.out.println("HashCode of bike11:" + context.getBean("bike11", String.class).hashCode());
		System.out.println("HashCode of bike12:" + context.getBean("bike12", String.class).hashCode());
		System.out.println("HashCode of bike13:" + context.getBean("bike13", String.class).hashCode());
		System.out.println("HashCode of bike14:" + context.getBean("bike14", String.class).hashCode());
		System.out.println("HashCode of bike15:" + context.getBean("bike15", String.class).hashCode());
		System.out.println("HashCode of bike16:" + context.getBean("bike16", String.class).hashCode());
		System.out.println("HashCode of bike17:" + context.getBean("bike17", String.class).hashCode());
		System.out.println("HashCode of bike18:" + context.getBean("bike18", String.class).hashCode());
		System.out.println("HashCode of bike19:" + context.getBean("bike19", String.class).hashCode());
		System.out.println("HashCode of bike20:" + context.getBean("bike20", String.class).hashCode());
		System.out.println("HashCode of bike21:" + context.getBean("bike21", String.class).hashCode());
		System.out.println("HashCode of bike22:" + context.getBean("bike22", String.class).hashCode());
		System.out.println("HashCode of bike23:" + context.getBean("bike23", String.class).hashCode());
		System.out.println("HashCode of bike24:" + context.getBean("bike24", String.class).hashCode());
		System.out.println("HashCode of bike25:" + context.getBean("bike25", String.class).hashCode());
		System.out.println("HashCode of bike26:" + context.getBean("bike26", String.class).hashCode());
		System.out.println("HashCode of bike27:" + context.getBean("bike27", String.class).hashCode());
		System.out.println("HashCode of bike28:" + context.getBean("bike28", String.class).hashCode());
		System.out.println("HashCode of bike29:" + context.getBean("bike29", String.class).hashCode());
		System.out.println("HashCode of bike30:" + context.getBean("bike30", String.class).hashCode());
		System.out.println("HashCode of bike31:" + context.getBean("bike31", String.class).hashCode());
		System.out.println("HashCode of bike32:" + context.getBean("bike32", String.class).hashCode());
		System.out.println("HashCode of bike33:" + context.getBean("bike33", String.class).hashCode());
		System.out.println("HashCode of bike34:" + context.getBean("bike34", String.class).hashCode());
		System.out.println("HashCode of bike35:" + context.getBean("bike35", String.class).hashCode());
		System.out.println("HashCode of bike36:" + context.getBean("bike36", String.class).hashCode());
		System.out.println("HashCode of bike37:" + context.getBean("bike37", String.class).hashCode());
		System.out.println("HashCode of bike38:" + context.getBean("bike38", String.class).hashCode());
		System.out.println("HashCode of bike39:" + context.getBean("bike39", String.class).hashCode());
		System.out.println("HashCode of bike40:" + context.getBean("bike40", String.class).hashCode());
		System.out.println("HashCode of bike41:" + context.getBean("bike41", String.class).hashCode());
		System.out.println("HashCode of bike42:" + context.getBean("bike42", String.class).hashCode());
		System.out.println("HashCode of bike43:" + context.getBean("bike43", String.class).hashCode());
		System.out.println("HashCode of bike44:" + context.getBean("bike44", String.class).hashCode());
		System.out.println("HashCode of bike45:" + context.getBean("bike45", String.class).hashCode());
		System.out.println("HashCode of bike46:" + context.getBean("bike46", String.class).hashCode());
		System.out.println("HashCode of bike47:" + context.getBean("bike47", String.class).hashCode());
		System.out.println("HashCode of bike48:" + context.getBean("bike48", String.class).hashCode());
		System.out.println("HashCode of bike49:" + context.getBean("bike49", String.class).hashCode());
		System.out.println("HashCode of bike50:" + context.getBean("bike50", String.class).hashCode());
		System.out.println("HashCode of district1" + context.getBean("district1", String.class).hashCode());
		System.out.println("HashCode of district2" + context.getBean("district2", String.class).hashCode());
		System.out.println("HashCode of district3" + context.getBean("district3", String.class).hashCode());
		System.out.println("HashCode of district4" + context.getBean("district4", String.class).hashCode());
		System.out.println("HashCode of district5" + context.getBean("district5", String.class).hashCode());
		System.out.println("HashCode of district6" + context.getBean("district6", String.class).hashCode());
		System.out.println("HashCode of district7" + context.getBean("district7", String.class).hashCode());
		System.out.println("HashCode of district8" + context.getBean("district8", String.class).hashCode());
		System.out.println("HashCode of district9" + context.getBean("district8", String.class).hashCode());
		System.out.println("HashCode of district10" + context.getBean("district10", String.class).hashCode());
		System.out.println("HashCode of district11" + context.getBean("district11", String.class).hashCode());
		System.out.println("HashCode of district12" + context.getBean("district12", String.class).hashCode());
		System.out.println("HashCode of district13" + context.getBean("district13", String.class).hashCode());
		System.out.println("HashCode of district14" + context.getBean("district14", String.class).hashCode());
		System.out.println("HashCode of district15" + context.getBean("district15", String.class).hashCode());
		System.out.println("HashCode of district16" + context.getBean("district16", String.class).hashCode());
		System.out.println("HashCode of district17" + context.getBean("district17", String.class).hashCode());
		System.out.println("HashCode of district18" + context.getBean("district18", String.class).hashCode());
		System.out.println("HashCode of district19" + context.getBean("district19", String.class).hashCode());
		System.out.println("HashCode of district20" + context.getBean("district20", String.class).hashCode());
		System.out.println("HashCode of district21" + context.getBean("district21", String.class).hashCode());
		System.out.println("HashCode of district22" + context.getBean("district22", String.class).hashCode());
		System.out.println("HashCode of district23" + context.getBean("district23", String.class).hashCode());
		System.out.println("HashCode of district24" + context.getBean("district24", String.class).hashCode());
		System.out.println("HashCode of district25" + context.getBean("district25", String.class).hashCode());
		System.out.println("HashCode of district26" + context.getBean("district26", String.class).hashCode());
		System.out.println("HashCode of district27" + context.getBean("district27", String.class).hashCode());
		System.out.println("HashCode of district28" + context.getBean("district28", String.class).hashCode());
		System.out.println("HashCode of district29" + context.getBean("district29", String.class).hashCode());
		System.out.println("HashCode of district30" + context.getBean("district30", String.class).hashCode());
		System.out.println("HashCode of state1:" + context.getBean("state1", String.class).hashCode());
		System.out.println("HashCode of state2:" + context.getBean("state2", String.class).hashCode());
		System.out.println("HashCode of state3:" + context.getBean("state3", String.class).hashCode());
		System.out.println("HashCode of state4:" + context.getBean("state4", String.class).hashCode());
		System.out.println("HashCode of state5:" + context.getBean("state5", String.class).hashCode());
		System.out.println("HashCode of state6:" + context.getBean("state6", String.class).hashCode());
		System.out.println("HashCode of state7:" + context.getBean("state7", String.class).hashCode());
		System.out.println("HashCode of state8:" + context.getBean("state8", String.class).hashCode());
		System.out.println("HashCode of state9:" + context.getBean("state9", String.class).hashCode());
		System.out.println("HashCode of state10:" + context.getBean("state10", String.class).hashCode());
		System.out.println("HashCode of state11:" + context.getBean("state11", String.class).hashCode());
		System.out.println("HashCode of state12:" + context.getBean("state12", String.class).hashCode());
		System.out.println("HashCode of state13:" + context.getBean("state13", String.class).hashCode());
		System.out.println("HashCode of state14:" + context.getBean("state14", String.class).hashCode());
		System.out.println("HashCode of state15:" + context.getBean("state15", String.class).hashCode());
		System.out.println("HashCode of state16:" + context.getBean("state16", String.class).hashCode());
		System.out.println("HashCode of state17:" + context.getBean("state17", String.class).hashCode());
		System.out.println("HashCode of state18:" + context.getBean("state18", String.class).hashCode());
		System.out.println("HashCode of state19:" + context.getBean("state19", String.class).hashCode());
		System.out.println("HashCode of state20:" + context.getBean("state20", String.class).hashCode());
		System.out.println("HashCode of state21:" + context.getBean("state21", String.class).hashCode());
		System.out.println("HashCode of state22:" + context.getBean("state22", String.class).hashCode());
		System.out.println("HashCode of state23:" + context.getBean("state23", String.class).hashCode());
		System.out.println("HashCode of state24:" + context.getBean("state24", String.class).hashCode());
		System.out.println("HashCode of state25:" + context.getBean("state25", String.class).hashCode());
		System.out.println("HashCode of state26:" + context.getBean("state26", String.class).hashCode());
		System.out.println("HashCode of state27:" + context.getBean("state27", String.class).hashCode());
		System.out.println("HashCode of state28:" + context.getBean("state28", String.class).hashCode());
		System.out.println("HashCode of state29:" + context.getBean("state29", String.class).hashCode());
		System.out.println("HashCode of state30:" + context.getBean("state30", String.class).hashCode());

		
		
		
	}

}
